title:        Tool
description:  Github micro tooling
url:          https://aribn.github.io/github-micro-tool

version:      1.1.1

author:
  name:       'Ari Bader-Natal'
  email:      'ari@aribadernatal.com'
markdown:     kramdown
permalink:    pretty
highlighter:  rouge

exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md",".DS_Store"]
